version: '3.8'
services:
  codeserver:
    container_name: codeserver
    build:
      # Change context to desired language environment:
      # ./codeserver/python - Python development with pyenv
      # ./codeserver/angular - Angular development with Node.js
      # ./codeserver/java - Java development with OpenJDK & Maven
      # ./codeserver/php - PHP development with Composer & frameworks
      context: ./codeserver/python
      dockerfile: Dockerfile
    ports:
      - 8443:8443
    restart: unless-stopped
    environment:
      SUDO_PASSWORD: ${SUDO_PASSWORD:-password}
    volumes:
      - ./code:/config/workspace
      - ./codeserver/config:/config